"""Stable domain interfaces shared by IO, algorithms, inference, and UI."""

from .display import ColorDisplayMapping, GrayscaleDisplayMapping
from .geometry import resample_to_ras_grid
from .images import (
    AlphaSemantics,
    Capability,
    ColorSpace,
    ImageData,
    ImageSequence2D,
    ImageVolume,
    IntensitySemantics,
    RasterImage2D,
    SourceType,
    SpacingSource,
)
from .resampling import resample_segmentation_layer
from .studies import (
    STUDY_LAYER_SCHEMA_VERSION,
    CompressionKind,
    ContourLayer,
    ContourPath,
    DeidentificationStatus,
    FractionalType,
    GeometryDifference,
    GeometryMatchStatus,
    GeometryTransformRecord,
    ImageSeries,
    ImageStudy,
    InterpolationMode,
    LabelDefinition,
    LabelStatistics,
    Layer,
    LayerBase,
    LayerCreator,
    LayerPresentation,
    LayerReference,
    LayerValidationState,
    RasterizationSettings,
    ReferenceMatchReport,
    RegionOfInterest,
    SegmentationLayer,
    SegmentationValueType,
    SourceFormat,
    SourceReference,
    SpatialGeometry,
    TransformKind,
    VolumeLayer,
    WorldCoordinateConvention,
)
from .transforms import TransformOperation, TransformRecord

__all__ = [
    "AlphaSemantics",
    "Capability",
    "ColorSpace",
    "ImageData",
    "ImageSequence2D",
    "ImageVolume",
    "IntensitySemantics",
    "RasterImage2D",
    "SourceType",
    "SpacingSource",
    "STUDY_LAYER_SCHEMA_VERSION",
    "CompressionKind",
    "ContourLayer",
    "ContourPath",
    "DeidentificationStatus",
    "FractionalType",
    "GeometryDifference",
    "GeometryMatchStatus",
    "GeometryTransformRecord",
    "ImageSeries",
    "ImageStudy",
    "InterpolationMode",
    "LabelDefinition",
    "LabelStatistics",
    "Layer",
    "LayerBase",
    "LayerCreator",
    "LayerPresentation",
    "LayerReference",
    "LayerValidationState",
    "RasterizationSettings",
    "ReferenceMatchReport",
    "RegionOfInterest",
    "SegmentationLayer",
    "SegmentationValueType",
    "SourceFormat",
    "SourceReference",
    "SpatialGeometry",
    "TransformKind",
    "VolumeLayer",
    "WorldCoordinateConvention",
    "TransformOperation",
    "TransformRecord",
    "ColorDisplayMapping",
    "GrayscaleDisplayMapping",
    "resample_to_ras_grid",
    "resample_segmentation_layer",
]
