"""Provider-neutral teaching-assistant interfaces.

Importing this package never opens a network connection.  Providers use a
disabled transport unless the host application explicitly injects an enabled
transport implementation.
"""

from .artifacts import (
    ArtifactLabelDefinition,
    ArtifactPayload,
    ArtifactReview,
    ArtifactReviewDecision,
    ArtifactValidationStatus,
    CalibrationMethod,
    ClassScore,
    ClassScoresArtifact,
    DataConsistencyMethod,
    DerivedLayerDescription,
    DerivedLayerKind,
    LabelsArtifact,
    LLMArtifactResponse,
    LLMArtifactType,
    LLMInputKind,
    LLMInputReference,
    LLMTaskKind,
    LLMTaskRequest,
    Mask2DArtifact,
    Mask3DArtifact,
    MaskValueSemantics,
    ProviderResponseMetadata,
    ReconstructedImageArtifact,
    ReconstructedVolumeArtifact,
    ReconstructionEvidence,
    ScoreSemantics,
    SemanticLabel,
    SpatialArtifactReference,
    TextArtifact,
    encode_npy,
)
from .providers import (
    AnthropicProvider,
    DeepSeekProvider,
    GenericOpenAICompatibleProvider,
    GLMProvider,
    KimiProvider,
    LLMProvider,
    MoonshotProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
)
from .transport import DisabledTransport, HttpRequest, Transport, UrllibTransport
from .types import (
    CLOUD_PREVIEW_PRIVACY_WARNING,
    EDUCATIONAL_DISCLAIMER,
    ChatMessage,
    ChatRole,
    CloudTransferDenied,
    LLMResponse,
    ProviderCapabilities,
    RenderedPreview,
    TransferItem,
    TransferPlan,
)

__all__ = [
    "AnthropicProvider",
    "ArtifactLabelDefinition",
    "ArtifactPayload",
    "ArtifactReview",
    "ArtifactReviewDecision",
    "ArtifactValidationStatus",
    "CalibrationMethod",
    "ChatMessage",
    "ChatRole",
    "CLOUD_PREVIEW_PRIVACY_WARNING",
    "CloudTransferDenied",
    "ClassScore",
    "ClassScoresArtifact",
    "DataConsistencyMethod",
    "DeepSeekProvider",
    "DisabledTransport",
    "DerivedLayerDescription",
    "DerivedLayerKind",
    "EDUCATIONAL_DISCLAIMER",
    "GLMProvider",
    "GenericOpenAICompatibleProvider",
    "HttpRequest",
    "KimiProvider",
    "LLMProvider",
    "LLMResponse",
    "LLMArtifactResponse",
    "LLMArtifactType",
    "LLMInputKind",
    "LLMInputReference",
    "LLMTaskKind",
    "LLMTaskRequest",
    "LabelsArtifact",
    "Mask2DArtifact",
    "Mask3DArtifact",
    "MaskValueSemantics",
    "MoonshotProvider",
    "OpenAICompatibleProvider",
    "OpenAIProvider",
    "ProviderCapabilities",
    "ProviderResponseMetadata",
    "ReconstructedImageArtifact",
    "ReconstructedVolumeArtifact",
    "ReconstructionEvidence",
    "RenderedPreview",
    "ScoreSemantics",
    "SemanticLabel",
    "SpatialArtifactReference",
    "TextArtifact",
    "Transport",
    "TransferItem",
    "TransferPlan",
    "UrllibTransport",
    "encode_npy",
]
